### ISSUE TITLE
How to transfer these code to pytorch? 

### ISSUE THREAD

**Issue by pengzhangzhi** [srush/GPU-Puzzles#1]
Hi. Thank you for sharing such an amazing tutorials. I have learned a lot from your tensor puzzles. : )
I have the following questions.

I am new to GPU programming (stuffs like numba) and have not idea of how those framework connected together. I am wondering that how to transfer the code written by following your tutorials to pytorch? It is very common in my workflow that I feel like writing some efficient algorithms for a neural network.

 In current deep learning researches, where large-scale models emerges rapidly, the efficiency has become the major bottleneck.  I thank being able to write low-level code is a must-have skills for DL researchers to develop modern neural networks. Would you like to share some additional resources (e.g., tutorials, courses) related to that? If you think the resources are important, I am willing to collects them and submit a pr to your repo to benefit more and more DL researchers.

Thanks again for your selflessness.

Best,
Zhangzhi

**Comment by pengzhangzhi** [comment]
A stupid question 

> I recommend doing these in Colab, as it is easy to get started.  Be
> sure to make your own copy, turn on GPU mode in the settings, and
> then get to coding.
How to turn on GPU mode in colab?

**Comment by jcupitt** [comment]
Oh, that's cool, thanks @srush.

Slight tangent: I noticed some unimportant spelling and grammar errors in this nice project. Would you be interested in a PR for these?

**Comment by srush** [comment]
That would be amazing thanks. Didn't expect these to take off so quickly. 

If you haven't already started, could you make them in this file: https://github.com/srush/GPU-Puzzles/blob/main/GPU_puzzlers.py . Notebook PRs are hard.
