### ISSUE TITLE
Puzzel 10 minimum global reads?

### ISSUE THREAD

**Issue by qihuazhong** [srush/GPU-Puzzles#10]
Puzzel 10 Dot product states that "You have 1 thread per position. You only need 1 global read and 1 global write per thread".

I am rather confused by this hint. This problem has two inputs, a and b, of the same size. Merely reading the elements of these two inputs at each thread count as TWO global reads already which exceeds the expectation of 1 global read.

Is the expectation supposed to be 2 global reads or am I missing some kind of trick? Thank you!

**Comment by srush** [comment]
Sorry this is a bug. It should be 2 global reads.

**Comment by qihuazhong** [comment]
> Sorry this is a bug. It should be 2 global reads.

Thanks for the clarification!
