### ISSUE TITLE
Puzzles 1

### ISSUE THREAD

**Issue by Yihan-zh** [srush/GPU-Puzzles#16]
out[local_i] = map_spec(a[local_i])
out[local_i] = a[local_i] + 10

The first command gets an error:
Untyped global name 'map_spec': cannot determine Numba type of <class 'function'>

The second one successes 

Did I miss some basic concepts?

**Comment by srush** [comment]
Map_spec is the unit test that tells you what your function should do. You cannot actually call it in the GPU code.

**Comment by Yihan-zh** [comment]
Thank you.
