### ISSUE TITLE
Hint for Q11: 1D Convolution

### ISSUE THREAD

**Issue by shenoynikhil98** [srush/GPU-Puzzles#17]
Currently my solution which passes the first test within the required constraints (2 global reads and 1 global write)
```python
MAX_CONV = 4
TPB = 8
TPB_MAX_CONV = TPB + MAX_CONV
def conv_test(cuda):
    def call(out, a, b, a_size, b_size) -> None:
        shared = cuda.shared.array(TPB_MAX_CONV, numba.float32)
        i = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x
        local_i = cuda.threadIdx.x

        # FILL ME IN (roughly 17 lines)
        if i < a_size:
            shared[local_i] = a[i]
            if i < b_size:
                shared[TPB + local_i] = b[i]
            cuda.syncthreads()

            # compute conv
            s = 0
            for j in range(b_size):
                if local_i + j < a_size:
                    s += shared[local_i + j] * shared[j + TPB]
            out[i] = s

    return call
```
I am stuck with the second test where the blocks increase. Is there a way to do this with the current shared memory size (`TPB_MAX_CONV`)

**Comment by srush** [comment]
The key thing to remember is that shared memory is *per block* so if it is two blocks you get that same shared memory twice. One chunk for the first block and one for the second. Threads only see the shared memory for their block.

**Comment by shenoynikhil98** [comment]
Are we allowed to extend the shared memory space to `TPB + MAX_CONV + (MAX_CONV - 1)` since, for the convolution on the last few indices in the first block, we would need access? Currently, my max global reads are increasing to `4` and write to `1`

**Comment by srush** [comment]
Ah, yes sorry. You are allowed to have multiple shared memory arrays.

**Comment by shenoynikhil98** [comment]
Thanks a lot!
