### ISSUE TITLE
Why would puzzle 14 - Matrix Multiply need shared memory?

### ISSUE THREAD

**Issue by CWEzio** [srush/GPU-Puzzles#18]
Here is my solution to puzzle 14
```python
        a_shared = cuda.shared.array((TPB, TPB), numba.float32)
        b_shared = cuda.shared.array((TPB, TPB), numba.float32)

        i = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x
        j = cuda.blockIdx.y * cuda.blockDim.y + cuda.threadIdx.y
        local_i = cuda.threadIdx.x
        local_j = cuda.threadIdx.y
        # FILL ME IN (roughly 14 lines)
        val = 0
        if i < size and j < size:
          for k in range(size):
                    val += a[i,k] * b[k,j]
          out[i, j] = val
```
I find that I can pass the two tests but I haven't use the shared memory. I feel that my solution is not correct but I don't know why the shared memory is needed here. Thank you for your answer!

**Comment by shenoynikhil98** [comment]
You would not be complying with the global reads limit (6 in this case).

**Comment by srush** [comment]
More specifically if you think about this code, each thread is reading everything it needs from global memory. That means there are `size` number of reads for each thread. These reads take up most of the time, so this is incredibly slow. 

For the correct solution, you will find that many of the reads are shared between threads. This allows you to do the computation much faster, and in fact is one of the key facets on modern DL (and why things like Attention are so fast).

**Comment by CWEzio** [comment]
Thank you for your answer!
