### ISSUE TITLE
Puzzle 13 - Incorrect Problem Statement

### ISSUE THREAD

**Issue by Pbatch** [srush/GPU-Puzzles#19]
The current statement for problem 13 reads:
"Implement a kernel that computes a sum over each row of a and stores it in out."

It should read:
"Implement a kernel that computes a sum over each _column_ of a and stores it in out."

This is evident by the fact that out is of length 4, and only solutions which sum the columns are said to be correct.

**Comment by srush** [comment]
Thanks! will fix.

**Comment by man-shar** [comment]
So, I'm new to numpy world and I might be getting this wrong, but I think the problem statement is still a little incorrect.

The input of this problem statement looks like this:

```
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])
```

But the output being checked against is 
```
Spec : [[ 15.]
 [ 51.]
 [ 87.]
 [123.]]
```

It seems to still be summing the rows? Or is my understanding of rows/columns twisted relative to numpy?
