### ISSUE TITLE
Any tips on using 1 global read for dot product (puzzle 10)?

### ISSUE THREAD

**Issue by yenchenlin** [srush/GPU-Puzzles#4]
The question stated that
> You only need 1 global read and 1 global write per thread.

However, loading both `a[i]` and `b[i]` into the shared memory costs 2 global reads for each thread. 
May I know if there are any hints on satisfying the puzzle's requirement?

**Comment by srush** [comment]
This is currently a big. Sorry, you can't do this with 1 global read 2 is fine.

Currently the score counter will count it as 1 if you read and multiply simultaneously. (Which needs to be fixed).
