### ISSUE TITLE
More general solution for Puzzle 9 (pooling)?

### ISSUE THREAD

**Issue by irapha** [srush/GPU-Puzzles#5]
my solution to puzzle 9 is very specific to pooling kernels of size=3

(spoilers ahead for my solutions)

```python
if i < size:
  shared[local_i] = a[local_i]
  cuda.syncthreads()

  if (local_i - 2) >= 0:
    shared[local_i] = shared[local_i] + shared[local_i -1] + shared[local_i -2]
  elif (local_i - 1) >= 0:
    shared[local_i] = shared[local_i] + shared[local_i -1]
  cuda.syncthreads()

if i < size:
  out[local_i] = shared[local_i]
```

my other attempt, which tried to be more generic in the pooling kernel size, seems to double-count something:

```python
if i < size:
  shared[local_i] = a[local_i]
  cuda.syncthreads()

  for j in [-2, -1]:
    if (local_i + j) >= 0:
      shared[local_i] = shared[local_i] + shared[local_i + j]
  cuda.syncthreads()

if i < size:
  out[local_i] = shared[local_i]
```

i figured something weird happens when it tries to do += twice on the same shared[local_i]
i.e.: that it might be double-counting shared[local_i]
however, it fails the test in a way that doesn't seems to align with this:
Yours: [ 0.  1.  3.  6. 10. 14. 18. 22.]
Spec : [ 0.  1.  3.  6.  9. 12. 15. 18.]

looking for any hints on a more general approach, or what is wrong with my solutions

**Comment by Ruibin-Liu** [comment]
The test code uses one block with block size 8 for 8 number so that your first attempt worked. I was stuck at how to generate to multiple blocks, say 2 blocks of size 4 for 8 numbers. 

For your second attempt, should you put the `cuda.syncthreads()` in the loop?

**Comment by Ruibin-Liu** [comment]
For your second attempt, you are writing and reading at the same time for each element in the `shared` array.
I was able to pass the test by using a local variable for each thread to store the sum and assign the local sum to `out` after the second `cuda.syncthreads()` call.

**Comment by irapha** [comment]
ah, i didn't think using helper python variables would work, i figured the shared arrays were the only allowed helpers

**Comment by srush** [comment]
Ah sorry, yes local scalar variables are allowed.  I will add to the docs.
