### ISSUE TITLE
Puzzle 11 issue creating shared array

### ISSUE THREAD

**Issue by TrentBrick** [srush/GPU-Puzzles#6]
My code does this: 
`a_s = cuda.shared.array(a_size, numba.float32)`

And I get this error: 

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function shared.array at 0x7f48d83f9050>) found for signature:
 
 >>> array(int64, class(float32))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload of function 'array': File: numba/cuda/cudadecl.py: Line 44.
        With argument(s): '(int64, class(float32))':
       No match.

During: resolving callee type: Function(<function shared.array at 0x7f48d83f9050>)
During: typing of call at <ipython-input-150-4bdb1f01d70a> (11)


File "<ipython-input-150-4bdb1f01d70a>", line 11:
    def call(out, a, b, a_size, b_size) -> None:
        <source elided>
        #print(type(a_size), type(SIZE))
        a_s = cuda.shared.array(a_size, numba.float32)
```

If I replace `a_size` with the global variable `SIZE` then things run correctly but this fails to generalize to the later tests where `a_size` changes.

**Comment by TrentBrick** [comment]
Both are type `int` so I'm not sure where this error is coming from

**Comment by TrentBrick** [comment]
Also the error is only when I call `problem.check()` not `problem.show()`

**Comment by srush** [comment]
CUDA is *extremely* strict about the sizes allowed for shared arrays. They are not allowed to be variables. They can only be constants at compile time. 

It's pretty crazy, but you cannot even pass them as variables. You have to either write a constant value i.e. 10 or give it a variable like TPB = 10 that was constant outside the function.
