### ISSUE TITLE
Puzzle 12 log_2 implementation?

### ISSUE THREAD

**Issue by TrentBrick** [srush/GPU-Puzzles#7]
I want log_2() function. Any tips on how I can implement this with numba? It looks like even the natural log doesn't run?

Eg. `int(math.log(size))` returns: 

```
LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No definition for lowering <built-in function log>(int64,) -> float64

File "<ipython-input-235-5ed9de693fee>", line 9:
    def call(out, a, size: int) -> None:
        <source elided>

        num_steps = int(math.log(size))
        ^

During: lowering "$58call_method.25 = call $54load_method.23(size, func=$54load_method.23, args=[Var(size, <ipython-input-235-5ed9de693fee>:4)], kws=(), vararg=None)" at <ipython-input-235-5ed9de693fee> (9)
``` 

Update: I just hard coded the log_2 results for now.

**Comment by srush** [comment]
Yeah as far as I know this doesn't exist in cuda. I can vouch though that you can do this function without taking logs. Remember max sizes will always be hard coded in cuda.

**Comment by Ruibin-Liu** [comment]
You can also calculate log2(TPB) out the the function def and make it a global variable.
